<?php
/*
 * Copyright (c) 2020. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Cart2Quote\Desk\Block\Product\View\Enquiry\Success $block */
?>
<div class="block-content ticket-enquiry-form-content" id="enquiry_success_modal_popup" style="display: none;">
    <div class="enquiry-icon enquiry-success enquiry-animate-success-icon" style="display: flex;">
        <div class="enquiry-success-circular-line-left" style="background-color: rgb(255, 255, 255);"></div>
        <span class="enquiry-success-line-tip"></span>
        <span class="enquiry-success-line-long"></span>
        <div class="enquiry-success-ring"></div>
        <div class="enquiry-success-fix" style="background-color: rgb(255, 255, 255);"></div>
        <div class="enquiry-success-circular-line-right" style="background-color: rgb(255, 255, 255);"></div>
    </div>
</div>
