<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>

<?php /**@var $block \MageWorx\DownloadsImportExport\Block\Adminhtml\Attachment\ImportExport */ ?>

<div class="import-export-downloads-attachment">
    <?php if (!$block->getIsReadonly()): ?>
        <div class="import-downloads-attachments">
            <?php if ($block->getUseContainer()): ?>
            <form id="import-form" class="admin__fieldset"
                  action="<?= $block->getUrl('mageworx_downloads/attachment/importPost') ?>" method="post"
                  enctype="multipart/form-data">
                <?php endif; ?>
                <?= $block->getBlockHtml('formkey') ?>
                <div class="fieldset admin__field">
                    <label for="import_attachments_file" class="admin__field-label">
                        <span><?= __('Import Attachments') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="file" id="import_attachments_file" name="import_attachments_file"
                               class="input-file required-entry"/>
                        <?= $block->getButtonHtml(__('Import Attachments'), '', 'import-submit') ?>
                    </div>
                </div>
                <div class="fieldset admin__field">
                    <label for="skip_products" class="admin__field-label">
                        <span><?= __('Skip Product Checks') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="skip_products" name="skip_products" class="checkbox"/>
                    </div>
                </div>
                <div class="fieldset admin__field">
                    <label for="skip_files" class="admin__field-label">
                        <span><?= __('Skip File Checks') ?></span>
                        <div class="admin__field-note">
                            <span><?php /* @escapeNotVerified */ echo __("Attachments won't be added for skipped records.")?></span>
                        </div>
                    </label>
                    <div class="admin__field-control">
                        <input type="checkbox" id="skip_files" name="skip_files" class="checkbox"/>
                    </div>
                </div>
                <?php if ($block->getUseContainer()): ?>
            </form>
        <?php endif; ?>
            <script>
                require(['jquery', 'Magento_Ui/js/modal/alert', 'mage/mage', 'loadingPopup', 'mage/translate'], function (jQuery, uiAlert) {

                    jQuery('#import-form').mage('form').mage('validation');
                    (function ($) {
                        $('.import-submit').click(function () {
                            if ($(':input[name="import_attachments_file"]').val()) {
                                $('body').loadingPopup({
                                    timeout: false
                                });

                                $(this.form).submit();
                            } else {
                                uiAlert({
                                    content: $.mage.__('Please select a file to import!')
                                });
                            }
                        });
                    })(jQuery);
                });
            </script>
        </div>
    <?php endif; ?>
    <div class="export-downloads-attachments <?php if ($block->getIsReadonly()): ?>box-left<?php else: ?>box-right<?php endif; ?>">
        <?php if ($block->getUseContainer()): ?>
        <form id="export_form" class="admin__fieldset" action="<?= $block->escapeHtmlAttr($block->getUrl('mageworx_downloads/attachment/exportCsv')) ?>" method="post" enctype="multipart/form-data">
            <?php endif; ?>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="fieldset admin__field">
                <span class="admin__field-label"><span><?= $block->escapeHtml(__('Export Attachments')) ?></span></span>
                <div class="admin__field-control">
                    <?= $block->getButtonHtml(__('Export Attachments'), "export_form.submit()") ?>
                </div>
            </div>
            <?php if ($block->getUseContainer()): ?>
        </form>
    <?php endif; ?>
    </div>
</div>
<br>
<div class="example-export">
    <?php if ($block->getUseContainer()): ?>
    <form id="example_export_form"
          class="admin__fieldset"
          action="<?php echo $block->getUrl('mageworx_downloads/attachment/exportExamplePost') ?>"
          method="post"
          enctype="multipart/form-data">
        <?php endif; ?>
        <?php echo $block->getBlockHtml('formkey') ?>
        <div class="fieldset admin__field">
                <span class="admin__field-label">
                    <span><?php echo __('Download example CSV file'); ?></span>
                </span>
            <div class="admin__field-control" style="line-height: 32px;">
                <a href="<?php echo $block->getUrl(
                    'mageworx_downloads/attachment/exportExamplePost'
                ) ?>"><?php echo __('Download'); ?></a>
            </div>
        </div>
        <?php if ($block->getUseContainer()): ?>
    </form>
<?php endif; ?>
</div>
