<script type="text/javascript">
    require(['jquery'],function () {
        
        /*(function ($, undefined) {
            $.extend({
                "stickysidebarscroll": function (el, config) {
                    if (config && config.offset) {
                        config.offset.bottom = parseInt(config.offset.bottom, 10);
                        config.offset.top = parseInt(config.offset.top, 10);
                    } else {
                        config.offset = {bottom: 100, top: 0};
                    }
                    var el = $(el);
                    if (el && el.offset()) {
                        var el_top = el.offset().top,
                            el_left = el.offset().left,
                            el_height = el.outerHeight(true),
                            el_width = el.outerWidth(),
                            el_position = el.css("position"),
                            el_position_top = el.css("top"),
                            el_margin_top = parseInt(el.css("marginTop"), 10),
                            doc_height = $(document).height(),
                            max_height = $(document).height() - config.offset.bottom,
                            top = 0,
                            swtch = false,
                            locked = false,
                            pos_not_fixed = false;
                        if (config.forcemargin === true || navigator.userAgent.match(/\bMSIE (4|5|6)\./) || navigator.userAgent.match(/\bOS (3|4|5|6)_/) || navigator.userAgent.match(/\bAndroid (1|2|3|4)\./i)) {
                            pos_not_fixed = true;
                        }
                        $(window).bind('scroll resize orientationchange load', el, function (e) {
                            if (doc_height !== $(document).height()) {
                                max_height = $(document).height() - config.offset.bottom;
                                doc_height = $(document).height();
                            }
                            //Offset can change due to dynamic elements at the top. So measure it everytime.
                            if (locked == false) {
                                el_top = el.offset().top;
                            }
                            var el_height = el.outerHeight(),
                                scroll_top = $(window).scrollTop();
                            //if we have a input focus don't change this (for ios zoom and stuff)
                            if (pos_not_fixed && document.activeElement && document.activeElement.nodeName === "INPUT") {
                                return;
                            }
                            locked = true;
                            if (scroll_top >= (el_top - (el_margin_top ? el_margin_top : 0) - config.offset.top)) {
                                if (max_height < (scroll_top + el_height + el_margin_top + config.offset.top)) {
                                    top = (scroll_top + el_height + el_margin_top + config.offset.top) - max_height;
                                } else {
                                    top = 0;
                                }
                                if (pos_not_fixed) {
                                    //if we have another element above with a new margin, we have a problem (double push down)
                                    //recode to position: absolute, with a relative parent
                                    el.css({'marginTop': parseInt(((el_margin_top ? el_margin_top : 0) + (scroll_top - el_top - top) + 2 * config.offset.top), 10) + 'px'});
                                } else {
                                    el.css({
                                        'position': 'fixed',
                                        'top': (config.offset.top - top) + 'px',
                                        'width': el_width + "px"
                                    });
                                }
                            } else {
                                locked = false;
                                el_left = el.offset().left;
                                el.css({
                                    'position': el_position,
                                    'top': el_position_top,
                                    'left': el_left,
                                    'width': el_width + "px",
                                    'marginTop': (el_margin_top ? el_margin_top : 0) + "px"
                                });
                            }
                        });
                    }
                }
            });
        })(jQuery);*/
        function sameHeightBlock() {
            var newProHeight = jQuery('.slideshow-wrapper .col-sm-18 .cdz-products').outerHeight();
            newProHeight = newProHeight-30;
            newProHeight = newProHeight/2;
            jQuery('.slideshow-wrapper .col-sm-6 .blocknew').css("min-height",newProHeight+"px");
        }
        jQuery(document).ready(function ($) {
            setInterval(function () {
                sameHeightBlock();
            },1);
           
            var bottomTopOffset = $('.page-footer #topfooter').offset().top;
            bottomTopOffset = bottomTopOffset-30;
            /*$.stickysidebarscroll(".cwsFeatured", {offset: {top: 30, bottom: bottomTopOffset}});*/
        });

        var $main = jQuery("main");
        var $header = jQuery("header");
        var $footer = jQuery("footer");
        var $floatBar = jQuery(".sidebar-main .cwsFeatured");
        var headerHeight = $header.outerHeight() + $header.offset().top;
        var leftPos = 0;
        var leftSize = 0;

        jQuery(window).scroll(function (event) {
            event.preventDefault();
            var $win = jQuery(this);
            var newHeight = 0;
            leftSize = $main.offset().left + 10 - leftPos;
            var $floatBarWidth = $floatBar.parent('.sidebar-main').outerWidth();
            var stickyParentTop = $floatBar.parent('.sidebar-main').offset().top;
            var diff = ($win.scrollTop() - stickyParentTop) + 20;

            var floatBarOffset = 0;
            var floatBarHeight = $footer.outerHeight();
            var generalSidebarHeight = $floatBar.outerHeight();
            var floatBarStopperPosition = $footer.offset().top;
            var stopPoint = floatBarStopperPosition - generalSidebarHeight - floatBarOffset;

            if(jQuery('.sticky-menu.active').length > 0)
                newHeight = jQuery('.sticky-menu.active').height();
            var curWinTop = $win.scrollTop() + newHeight;
            if (stopPoint - 30 < curWinTop) {
                //var diff1 = stopPoint - generalSidebarHeight - 30;
                var diff1 = stopPoint - 30;
                $floatBar.css({
                    width: $floatBarWidth -20,
                    left: 10,
                    position: 'absolute',
                    //top: diff - floatBarHeight - 30,
                    top: diff1 - floatBarHeight,
                    bottom: 'auto'
                })
            } else if(curWinTop > stickyParentTop){
                $floatBar.css({
                    width: $floatBarWidth -20,
                    left: 10,
                    position: 'absolute',
                    top: diff + 30,
                    bottom: 'auto'
                })
            }
            else {
                $floatBar.css({
                    width: $floatBarWidth -20,
                    position: 'static',
                    top: 'auto',
                    left: 'auto'
                })
            }
        });
    });
</script>

