<?php
/**
 * Copyright (c) 2019. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Cart2Quote\Desk\Block\Customer\Ticket\View\Message $block */
?>

<?php $ticket = $block->getTicketData() ?>
<form id="desk_message_form"
      action="<?php echo $block->getUrl('desk/ticket/update') ?>"
      data-ticket-id="<?php echo $block->getTicketId() ?>"
      data-header-translation="<?php echo __("Ticket #%1") ?>"
      data-mage-init='{"desk.form.message":{}, "validation":{}}'>
    <?php echo $block->getChildHtml() ?>
</form>