<?php
/**
 * Copyright (c) 2019. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Cart2Quote\Desk\Block\Customer\Ticket\View\Message $block */
?>
<?php $ticket = $block->getTicketData() ?>
<?php if ($ticket->getId() && !$block->canEditTitle()): ?>
    <div class="ticket-subject">
        <div class="ticket-subject-value">
            <input name="ticket[subject]"
                   type="text"
                   value="<?php echo $ticket->getSubject()?>"
                   placeholder="<?php echo __("Enter Subject") ?>"
                   id="ticket-subject"
                   readonly
                   class="input-text" />
        </div>
    </div>
<?php else: ?>
    <div class="ticket-subject">
        <div class="ticket-subject-value special-title">
            <input name="ticket[subject]"
                   type="text"
                   value="<?php echo $ticket->getSubject()?>"
                   placeholder="<?php echo __("Enter Subject") ?>"
                   id="ticket-subject"
                   class="input-text required-entry" />
        </div>
    </div>
<?php endif; ?>
<div class="create-message">
        <textarea name="message[message]"
                  id="comment"
                  title="What’s on your mind?"
                  class="input-text"
                  cols="5" rows="3"
                  data-validate="{required:true}"
                  aria-required="true"
                  placeholder="<?php echo __("Enter your message") ?>"></textarea>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="">
            <button type="submit" title="Submit" class="action submit primary" id="send-message-button">
                <span><?php echo __("Send") ?></span>
            </button>
        </div>
    </div>
</div>
