<script type="text/x-magento-init">
{	"*":{
		"Magento_Theme/js/fastest_bigmarket":{}
	}
}
</script>
<script>

require(["jquery"], function($){
 /// jQuery(document).ready( function() {
    /*
         jQuery(" div.selected").on("click", function () {
          var hasActiveClass = jQuery("div.select-box").hasClass("active");
    
          if (hasActiveClass === false) {
              var windowHeight =jQuery(window).outerHeight();
              var dropdownPosition = jQuery(this).offset().top;
              var dropdownHeight = 95; // dropdown height
    
              if (dropdownPosition + dropdownHeight + 50 > windowHeight) {
                  jQuery("div.select-box").addClass("drop-up");
              }
              else {
                 jQuery("div.select-box").removeClass("drop-up");
              }
    
              var currentUniversity = jQuery(this).find('text').text().trim();
    
              jQuery.each(jQuery("ul.select-list li"), function () {
                  var university = jQuery(this).text().trim();
                  if (university === currentUniversity)
                      jQuery(this).addClass("active");
                  else
                      jQuery(this).removeClass("active");
              });
          }
    
          jQuery("div.select-box").toggleClass("active");
      });

      jQuery("ul.select-list li").on("click", function () {
          var university = jQuery(this).html();
          jQuery("span.text").html(university);
          jQuery("div.select-box").removeClass("active");
      });
    
      jQuery("ul.select-list li").hover(function () {
          jQuery("ul.select-list li").removeClass("active");
      });
    
      jQuery(document).click(function (event) {
          if (jQuery(event.target).closest("div.custom-select").length < 1) {
              jQuery("div.select-box").removeClass("active");
          }
      });
      
      */
    ///  });
});
</script>