<div class="block block-compare quote">
    <div class="block-title">
        <strong id="block-compare-heading">My Quote</strong>
    </div>
    <div class="block-content">
        <ol id="compare-items" class="product-items product-items-names">
<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
    $customerSession->getCustomerId();  // get Customer Id

   $emailCus = $customerSession->getCustomer()->getEmail(); // get Email

   $resource = $objectManager->create('Magento\Framework\App\ResourceConnection');
  $connection = $resource->getConnection();
  $getTableQuote = $resource->getTableName('quote');
  $getTableQuote_item = $resource->getTableName('quote_item'); 
       $get_customer_time = "Select * FROM ".$getTableQuote." WHERE customer_email = '".$emailCus."' ORDER BY entity_id DESC";
       $array_quote = $connection->fetchAll($get_customer_time);
       // var_dump($array_quote);
       if (empty($array_quote)){?>
          <div class="empty">You have no items in your quote list.</div>
       <?php }else {


       foreach ($array_quote as $key_quote) {
          $getId = $key_quote['entity_id'];
          $get_active = $key_quote['is_active'];
          $get_qty = $key_quote['items_count'];
          break;
       }

       if($get_active != 0){
          $get_quote_item = "Select * FROM ".$getTableQuote_item." WHERE quote_id = '".$getId."' AND parent_item_id IS NULL  ORDER BY item_id DESC LIMIT ".$get_qty;
        $array_quote_items = $connection->fetchAll($get_quote_item);
        if (empty($array_quote_items)){?>
          <div class="empty">You have no items in your quote list.</div>
       <?php }else {
        $i = 0;
          foreach ($array_quote_items as $key_quotes) {
            $getName = $key_quotes['name'];
            $getId = $key_quotes['product_id'];
         
        $productRepository = $objectManager->get('\Magento\Catalog\Model\ProductRepository');
         
        // get product by product id
            $product = $productRepository->getById($getId); 
            $urlProduct = $product->getProductUrl();
            $imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image');
            $image_url = $imageHelper->init($product, 'product_page_image_small')->setImageFile($product->getFile())->resize(100, 100)->getUrl();
            ?>
            <li class="product-item">
                <img src="<?= $image_url; ?>" alt="<?= $getName; ?>">
                <strong class="product-item-name">
                    <a class="product-item-link" href="<?= $urlProduct;?>"><?= $getName; ?></a>
                </strong>
            </li>
          <?php
          } 
         }
       }else{?>
    <div class="empty">You have no items in your quote list.</div>
      <?php }
        }
}else{?>
  <div class="empty">Please  <a href="<?= $baseUrl; ?>customer/account/login">login</a> to see your quote.</div>
<?php }
?>
               
        </ol>
    </div>
</div>
<style type="text/css">
.block-compare.quote .product-item img {
    display: inline-block;
    vertical-align: middle;
}
.block-compare.quote .product-item .product-item-name {
  margin-left: 0;
    display: inline-block;
    max-width: 130px;
    vertical-align: middle;
}
.block.block-wishlist {
  display: none;
}
</style>