<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_ImageGallery
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $jsonConfig = $this->getGalleryJsonConfig();
    $imagesCollecton = $block->getGalleryImages();
?>
<div class="wk_imagegallery_container">
    <?php if($imagesCollecton): ?>
        <?php foreach ($imagesCollecton as $image): ?>
            <?php
                $title = $image->getTitle();
                $imageName = $image->getImage();
                $description = $image->getDescription();
                $imageUrl = $this->getImageUrl($imageName);
                $resizeUrl = $this->getResizedUrl($imageName);
            ?>
            <a href="<?php echo $imageUrl; ?>" title="<?php echo $description; ?>" class="imagegallery fancybox" data-fancybox-group="gallery">
                <img src="<?php echo $resizeUrl; ?>" class="wk_active wk_images wk_default" style="opacity:1;"/>
            </a>
        <?php endforeach; ?>
    <?php else: ?>
        <?php echo __('No Images in this gallery'); ?>
    <?php endif; ?>
</div>
<script type="text/javascript">
    require(['jquery','Webkul_ImageGallery/js/gallery'], function ($) {
        var jsonConfig = JSON.parse('<?php echo $jsonConfig; ?>');
        $(document).ready(function() {
            $(".fancybox").fancybox(jsonConfig);
        });
    });
</script>
