<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * Product viewed counter template
 *
 * @var $block \Magento\Catalog\Block\Ui\ProductViewCounter
 */
 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$app = $objectManager->get('Magento\Framework\App\Http\Context');
    if ($app->getValue('customer_logged_in')) {
?>
<script type="text/x-magento-init">
    {
        "*": {
                "Magento_Catalog/js/product/view/provider": {
                    "data": <?= /* @noEscape */ $block->getCurrentProductData() ?>
            }
        }
    }
</script>
<?php } ?>