<?php
/**
 * Copyright (c) 2023. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var \Cart2Quote\SalesRep\Block\Adminhtml\SalesRep\User $block */ ?>
<span class="salesrep-details" style="<?php echo $block->getShowSalesRep() ?>">
    <span class="salesrep-name">
        <?php echo $block->getName() ?>
    </span>
    <span class="salesrep-role">
        <?php echo $block->getRole() ?>
    </span>
</span>
<span class="salesrep-assign">
    <a  href="#"><?php echo $block->getActionLabel() ?></a>
</span>
