<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $block->getProduct(); 
$getId = $_product->getId(); 
$session = $objectManager->get('Magento\Customer\Model\Session');
$session->setTestKey($getId);
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart <?= $getId; ?>">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
				<div class="qty-minus"> <a class="btn-qty btn-qty-quickview minus" href="#">-</a></div>
				<div class="qty-input">
						<input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
				</div>
				<div class="qty-plus"> <a class="btn-qty btn-qty-quickview plus" href="#">+</a></div>
            </div>
        </div>
		 <script type="text/javascript">
		require(['jquery','domReady!'],function($){
			$(".btn-qty-quickview").click(function (event) {
				var $button = $(this);
				var oldValue = $button.closest('.control').find("input#qty").val();
				var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
				if ($button.hasClass('plus')) {
					console.log('here old:' + oldValue);
					var newVal = parseFloat(oldValue) + 1;
				} else {
					if (oldValue > defaultValue) {
					    var newVal = parseFloat(oldValue) - 1;
					} else {
					    newVal = defaultValue;
					}
				}
				
				console.log('end:' + newVal);
				$button.closest('.control').find("input#qty").val(newVal);
				event.preventDefault();
			});

		});
        </script>
        <?php endif; ?>
    </div>
	<div style="clear:both"></div>
</div>
<?php endif; ?>