<?php
/**
 * Copyright © Pronko Consulting
 * See LICENSE for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$successUrl = $block->getUrl('checkout/onepage/success');
?>
<html>
<meta http-equiv="refresh" content="0; URL=<?= $block->escapeXssInUrl($successUrl)?>">
<body>
<p><?= $block->escapeHtml(__('Your payment has been successfully processed by our website.')) ?></p>
<p>
    <?= $block->escapeHtml(__('Please click ')) ?>
    <a href="<?= $block->escapeXssInUrl($successUrl)?>"><?= $block->escapeHtml(__('here')) ?></a>
    <?= $block->escapeHtml(__(' if you are not redirected automatically.')) ?>
</p>
</body>
</html>
