<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * Wrapper for product attachments to include title
 *
 * @var \Magento\Framework\View\Element\Template $block
 */

$childHtml = $block->getChildHtml();

?>
<?php if (trim($childHtml) !== "") : ?>
    <div class="product-full-width-section">
        <h2 class="product-section-title">
            <?= $block->escapeHtml($block->getChildBlock('mageworx_product_attachments')->getSectionTitle()); ?>
        </h2>
        <?= $block->getChildHtml(); ?>
    </div>
<?php endif; ?>