<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_GroupedProductOption
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Bss\GroupedProductOption\Block\Product\View\Type\Configurable */
?>

<div class="swatch-opt" data-role="swatch-options-<?= $block->getProduct()->getId(); ?>"></div>

<script type="text/x-magento-init">
    {
        "[data-role=swatch-options-<?= $block->getProduct()->getId(); ?>]": {
            "bss/groupedProductOptionSwatch": {
                "jsonConfig": <?= /* @escapeNotVerified */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?php /* @noEscape */ echo $block->getJsonSwatchConfig(); ?>,
                <?php if ($block->isMagentoVersion('2.2.7')) : ?>
                "jsonSwatchImageSizeConfig": <?php /* @noEscape */ echo $block->getJsonSwatchSizeConfig() ?>,
                <?php endif; ?>
                "jsonGroupedConfigurable": <?php /* @noEscape */ echo $block->getJsonGroupedConfigurable(); ?>,
                "showTooltip": <?= $block->escapeJs($block->getShowSwatchTooltip()) ?>
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>
