<?php
/**
 * Copyright © MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \MageWorx\Downloads\Block\Widget\Sections */
$pseudoSections = $block->getGroupAttachments();
?>
<?php if (!empty($pseudoSections)): ?>
    <div class="widget block block-sections product-attachment-container">

        <?php if ($block->getTitle()): ?>
            <div class="block-title">
                <strong><?= $block->escapeHtml($block->getTitle()) ?></strong>
            </div>
        <?php endif; ?>

        <?php foreach ($pseudoSections as $pseudoSection): ?>
            <div class="section-title"><?= $block->escapeHtml($pseudoSection['title']); ?></div>
            <div class="section-files">

                <?php foreach ($pseudoSection['attachments'] as $item): ?>
                    <?= $block->getAttachmentHtml($item); ?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>

        <?php if ($block->isShowHowToDownloadMessage()): ?>
            <div class="access-notice"><span>* <?= /* @noEscape */
                    $block->getHowToDownloadMessage() ?></span></div>
        <?php endif; ?>
    </div>
<?php endif;
