<?php
/**
 * Copyright (c) 2019. Cart2Quote B.V. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Cart2Quote\Desk\Block\Magento\Contact\Success $block */
?>

<div class="form contact ticket-form-success-content" style="display:none;">
    <fieldset class="fieldset ticket-fieldset review-fieldset" data-hasrequired="<?php __("* Required Fields"); ?>">
        <legend class="legend review-legend ticket-legend">
            <span><?php echo __("Thank you for your question."); ?></span>
        </legend>
        <br/>
        <div class="actions-toolbar review-form-actions ticket-success-form-actions">
            <div class="primary actions-primary">
                <button type="submit"
                        class="action submit primary"
                        id="view-ticket-button"
                        data-ticket-id="0"
                        data-mage-init='{
                            "desk.view.ticket.button" : {
                                "bindOnClick": "1",
                                "url": "<?php echo $block->getUrl('desk/customer/view') ?>"
                            }
                        }'>
                    <span><?php echo __("View your ticket") ?></span>
                </button>
                <br/><br/>
                <button type="submit"
                        class="action submit"
                        data-mage-init='{ "desk.view.form.button" : {} }'>
                    <span><?php echo __("Ask a new question") ?></span>
                </button>
            </div>
        </div>
    </fieldset>
</div>
