<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_ImageGallery
 * @author    Webkul
 * @copyright Copyright (c) 2010-2016 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $myBlock = $objectManager->get('Webkul\ImageGallery\Block\Adminhtml\Groups\Edit\Tab\Gallery');
?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/confirm',
        'underscore',
        'mage/adminhtml/grid',
        'prototype'
    ], function(jQuery, confirm, _) {

    <?php if (is_object($myBlock) && $myBlock->getJsObjectName()): ?>
        var checkBoxes = $H(<?php echo $myBlock->getSelectedGalleryJson(); ?>);
        var warning = false;
        if (checkBoxes.size() > 0) {
            warning = true;
        }
        jQuery('#gallery_ids').val(checkBoxes.toQueryString());

        function registerGroupsGallery(grid, element, checked)
        {
            console.log(checkBoxes);
            if (checked) {
                checkBoxes.set(element.value, 0);
            } else {
                checkBoxes.unset(element.value);
            }
            $('gallery_ids').value = checkBoxes.toQueryString();
            grid.reloadParams = {'gallery_ids[]':checkBoxes.keys()};
        }

        function groupsGalleryRowClick(grid, event)
        {
            var trElement = Event.findElement(event, 'tr');
            var isInput   = Event.element(event).tagName == 'INPUT';
            if (trElement) {
                var checkbox = Element.getElementsBySelector(trElement, 'input');
                if(checkbox[0]){
                    var checked = isInput ? !checkbox[0].checked : checkbox[0].checked;
                    if (checked) {
                        checkbox[0].checked = false;
                        checkBoxes.unset(checkbox[0].value);
                        varienElementMethods.setHasChanges(checkbox[0]);
                        $('gallery_ids').value = checkBoxes.toQueryString();
                        grid.reloadParams = {
                            'gallery_ids[]': checkBoxes.keys()
                        };
                    } else {
                        checkbox[0].checked = true;
                        checkBoxes.set(checkbox[0].value, true);
                        $('gallery_ids').value = checkBoxes.toQueryString();
                        grid.reloadParams = {
                            'gallery_ids[]': checkBoxes.keys()
                        };
                    }
                }
            }
        }

        function groupsGalleryRowInit(grid, row)
        {
            var checkbox = $(row).getElementsByClassName('checkbox')[0];
            if (checkbox) {
                if (checkbox.checked) {
                    checkBoxes.set(checkbox.value, checkbox.checked);
                } else {
                    checkBoxes.unset(checkbox.value);
                }

                $('gallery_ids').value = checkBoxes.toQueryString();
                grid.reloadParams = {'gallery_ids[]':checkBoxes.keys()};
            }
        }

        function massSelectGallery(allCheckbox) {
            if (!allCheckbox.checked && _.size(checkBoxes._object) > 0) {
                allCheckbox.checked = true;
                allCheckbox.checked = false;
                markCheckboxes(false);
            } else {
                markCheckboxes(allCheckbox.checked)
            }
        }
        function markCheckboxes(value) {
            <?php echo $myBlock->getJsObjectName() ?>.rows.each(function(row)
            {
                $(row).getElementsByClassName('checkbox')[0].checked = value;
                groupsGalleryRowInit(<?php echo $myBlock->getJsObjectName() ?>, row);
            });
        }
        function onLoad() {
            if (typeof <?php echo $myBlock->getJsObjectName() ?> !== 'undefined') {
                <?php echo $myBlock->getJsObjectName() ?>.
                rowClickCallback = groupsGalleryRowClick;
                <?php echo $myBlock->getJsObjectName() ?>.
                initRowCallback = groupsGalleryRowInit;
                <?php echo $myBlock->getJsObjectName() ?>.
                checkboxCheckCallback = registerGroupsGallery;
                <?php echo $myBlock->getJsObjectName() ?>.
                checkCheckboxes = massSelectGallery;
                <?php echo $myBlock->getJsObjectName() ?>.
                rows.each(function (row) {
                    groupsGalleryRowInit(<?php echo $myBlock->getJsObjectName() ?>, row)
                });
                $('gallery_ids_old').value = $('gallery_ids').value;
            } else {
                setTimeout(onLoad, 300);
            }
        }
        onLoad();
    <?php endif; ?>
});
</script>
